### ISSUE TITLE
[Feature Request] Excluding mods

### ISSUE THREAD

**Issue by RozeFound** [tyra314/modweaver#4]
I have physics mod installed, but the author is uploading latest release only on own website. So, modweaver only downgrading this mod while trying to upgrade.

**Comment by tyra314** [comment]
That physics mod really caught me off guard. I was wondering, why modweaver could even identify the physics mod latest version downloaded from their website. Turns out, the newest version is sort of uploaded to CF. But the file is not "available" for display or download. They even faked the displayed name of the version:

```
        "displayName": "Physics 2.5.13 (Fabric - 1.17.1)",
        "fileName": "physics-mod-2.5.15-mc-1.17.1-fabric.jar",
```

I excluded not available files in the `discover` command and added a pin/unpin command. 

I don't know the reasoning behind the staged availability of releases, nor if newer versions will only be available on their website. So in this particular case, I think you should either live with the version available on CF, or manually update the physics mod from their website.
